parameters:
    generic_handler: IZiviPlanningBundle\Handler\GenericHandler

services:
    izivi.code.handler:
        class: IZiviPlanningBundle\Handler\CodeHandler
        arguments: [ "@doctrine.orm.entity_manager", IZiviPlanningBundle\Entity\Code,  "@service_container", "c", IZiviPlanningBundle\Form\CodeFormType]

    izivi.user.handler:
        class: IZiviPlanningBundle\Handler\UserHandler
        arguments: [ "@doctrine.orm.entity_manager", IZiviPlanningBundle\Entity\User,  "@service_container", "u", IZiviPlanningBundle\Form\UserFormType]

    izivi.state.handler:
        class: %generic_handler%
        arguments: [ "@doctrine.orm.entity_manager", IZiviPlanningBundle\Entity\State,  "@service_container", "c"]

    izivi.registration_center.handler:
        class: %generic_handler%
        arguments: [ "@doctrine.orm.entity_manager", IZiviPlanningBundle\Entity\RegistrationCenter,  "@service_container", "c"]

    izivi.tender.handler:
            class: %generic_handler%
            arguments: [ "@doctrine.orm.entity_manager", IZiviPlanningBundle\Entity\Tender,  "@service_container", "c"]

    izivi.employment.handler:
          class: %generic_handler%
          arguments: [ "@doctrine.orm.entity_manager", IZiviPlanningBundle\Entity\Employment,  "@service_container", "c", IZiviPlanningBundle\Form\EmploymentFormType]

    object_normalizer:
            class: Symfony\Component\Serializer\Normalizer\GetSetMethodNormalizer
            # Important! Tag this service or it wouldn't work
            tags:
                - { name: serializer.normalizer }

