version: "3"

services:
  mongodb:
    image: mongo:3.4
    hostname: mongodb
    volumes:
      - db-data:/data/db
    networks:
      - dbnet
    command: --noprealloc --smallfiles
    expose:
      - 27017
    restart: always
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  izivi-backend:
    image: izivi-backend:latest
    volumes:
      - uploaded-files:/bundle/programs/server/assets/a pp/uploads
    networks:
      - dbnet
      - webnet
    ports:
      - "8080:80"
    links:
      - mongodb:db
    environment:
      - NODE_ENV=production
      - PORT=80
      - MONGO_URL=mongodb://db/izivi
      - UI_ENDPOINT=http://localhost
      - ROOT_URL=http://localhost:8080
      # - OPTICS_API_KEY=xxxxx https://www.npmjs.com/package/optics-agent
      # - MAIL_URL=xxx https://docs.meteor.com/api/email.html
    restart: always
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  izivi-webui:
    image: izivi-webui:latest
    ports:
      - "80:3000" # This is the webui port
    networks:
      - webnet
    links:
      - izivi-backend:backend
    restart: always
    environment:
      - GRAPHQL_ENDPOINT=http://backend:8080/graphql # server side env! needs to point to internal address (izivi-backend)
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

volumes:
  db-data:
  uploaded-files:

networks:
  dbnet:
  webnet:
