i_zivi_planning_homepage:
    path:     /
    defaults: { _controller: IZiviPlanningBundle:Default:index }


codes:
    type:     rest
    resource: IZiviPlanningBundle\Controller\CodeController
    prefix:   /v1
    name_prefix:  api_1_
    defaults: { _format: json }

users:
    type:     rest
    resource: IZiviPlanningBundle\Controller\UserController
    prefix:   /v1
    name_prefix:  api_1_
    defaults: { _format: json }

states:
    type:     rest
    resource: IZiviPlanningBundle\Controller\StateController
    prefix:   /v1
    name_prefix:  api_1_
    defaults: { _format: json }

registration_centers:
    type:     rest
    resource: IZiviPlanningBundle\Controller\RegistrationCenterController
    prefix:   /v1
    name_prefix:  api_1_
    defaults: { _format: json }
