parameters:
    generic_handler: IZiviPlanningBundle\Handler\GenericHandler

services:
    izivi.code.handler:
        class: %generic_handler%
        arguments: [ "@doctrine.orm.entity_manager", IZiviPlanningBundle\Entity\Code,  "@service_container", "c", "iziviplanningbundle_codeformtype"]