parameters:
    generic_handler: IZiviPlanningBundle\Handler\GenericHandler

services:
    izivi.code.handler:
        class: IZiviPlanningBundle\Handler\CodeHandler
        arguments: [ "@doctrine.orm.entity_manager", IZiviPlanningBundle\Entity\Code,  "@service_container", "c", IZiviPlanningBundle\Form\CodeFormType]

    izivi.user.handler:
        class: IZiviPlanningBundle\Handler\UserHandler
        arguments: [ "@doctrine.orm.entity_manager", IZiviPlanningBundle\Entity\User,  "@service_container", "u", IZiviPlanningBundle\Form\UserFormType]

    object_normalizer:
            class: Symfony\Component\Serializer\Normalizer\GetSetMethodNormalizer
            # Important! Tag this service or it wouldn't work
            tags:
                - { name: serializer.normalizer }

