parameters:
    generic_handler: IZiviPlanningBundle\Handler\GenericHandler

services:
    izivi.code.handler:
        class: IZiviPlanningBundle\Handler\CodeHandler
        arguments: [ "@doctrine.orm.entity_manager", IZiviPlanningBundle\Entity\Code,  "@service_container", "c", "izivi.code.form.type"]


