# -*- mode: ruby -*-
# vi: set ft=ruby :

module OS
    def OS.windows?
        (/cygwin|mswin|mingw|bccwin|wince|emx/ =~ RUBY_PLATFORM) != nil
    end

    def OS.mac?
        (/darwin/ =~ RUBY_PLATFORM) != nil
    end

    def OS.unix?
        !OS.windows?
    end

    def OS.linux?
        OS.unix? and not OS.mac?
    end
end

Vagrant.configure("2") do |config|
    config.vm.define :izivi do |izivi|

        izivi.vm.box = "centos/7"
        izivi.vm.network :private_network, :ip => '192.168.122.11'
        izivi.vm.hostname = "izivi.test.local"
        izivi.vm.synced_folder "../", "/vagrant"

        izivi.vm.provider :libvirt do |domain|
            if ENV['REMOTE']
                domain.storage_pool_name = "vagrant"
                domain.host = "vmhost02"
                domain.connect_via_ssh = true
                domain.username = "root"
                domain.id_ssh_key_file = "id_rsa"
            end
            domain.disk_bus = "virtio"
            domain.memory = 4096
            domain.cpus = 2
            domain.volume_cache = 'writeback'
        end

        config.vm.provider "virtualbox" do |domain|
          host = RbConfig::CONFIG['host_os']

          # Give VM 1/4 system memory & access to all cpu cores on the host
          if host =~ /darwin/
            cpus = `sysctl -n hw.ncpu`.to_i
            # sysctl returns Bytes and we need to convert to MB
            mem = `sysctl -n hw.memsize`.to_i / 1024 / 1024 / 4
          elsif host =~ /linux/
            cpus = `nproc`.to_i
            # meminfo shows KB and we need to convert to MB
            mem = `grep 'MemTotal' /proc/meminfo | sed -e 's/MemTotal://' -e 's/ kB//'`.to_i / 1024 / 4
          else # sorry Windows folks, I can't help you
            cpus = 4
            mem = 4096
          end

          domain.customize ["modifyvm", :id, "--memory", mem]
          domain.customize ["modifyvm", :id, "--cpus", cpus]
        end

        # This shell provisioner installs librarian-puppet and runs it to install
        # puppet modules. After that it just runs puppet
        izivi.vm.provision :shell, :path => "shell/bootstrap.sh"
	end
end
